### PR TITLE
Update Project

### PR DESCRIPTION
**Pull request by nisrulz**
Updated some deps and added some helpful comments with links

### CODE REVIEW

**Review by martijnvanwelie — COMMENTED** [review]
Did you try running the examples on SDK 33? I am working on fully compatibility with that because some calls have been deprecated....

**Comment by nisrulz** [comment]
@martijnvanwelie I have only recently got the opportunity to look into this. I believe you are referring to these warnings when one builds the library:

```
> Task :blessed:compileReleaseKotlin
w: blessed-android-coroutines/blessed/src/main/java/com/welie/blessed/BluetoothCentralManager.kt:523:72 Parameter 'peripheralCallback' is never used
w: blessed-android-coroutines/blessed/src/main/java/com/welie/blessed/BluetoothPeripheral.kt:171:22 This declaration overrides deprecated member but not marked as deprecated itself. Please add @Deprecated annotation or suppress. See https://youtrack.jetbrains.com/issue/KT-47902 for details
w: blessed-android-coroutines/blessed/src/main/java/com/welie/blessed/BluetoothPeripheral.kt:177:46 'getter for value: ByteArray!' is deprecated. Deprecated in Java
w: blessed-android-coroutines/blessed/src/main/java/com/welie/blessed/BluetoothPeripheral.kt:183:22 This declaration overrides deprecated member but not marked as deprecated itself. Please add @Deprecated annotation or suppress. See https://youtrack.jetbrains.com/issue/KT-47902 for details
w: blessed-android-coroutines/blessed/src/main/java/com/welie/blessed/BluetoothPeripheral.kt:184:50 'getter for value: ByteArray!' is deprecated. Deprecated in Java
w: blessed-android-coroutines/blessed/src/main/java/com/welie/blessed/BluetoothPeripheral.kt:188:22 This declaration overrides deprecated member but not marked as deprecated itself. Please add @Deprecated annotation or suppress. See https://youtrack.jetbrains.com/issue/KT-47902 for details
w: blessed-android-coroutines/blessed/src/main/java/com/welie/blessed/BluetoothPeripheral.kt:194:50 'getter for value: ByteArray!' is deprecated. Deprecated in Java
w: blessed-android-coroutines/blessed/src/main/java/com/welie/blessed/BluetoothPeripheral.kt:369:41 'getParcelableExtra(String!): T?' is deprecated. Deprecated in Java
w: blessed-android-coroutines/blessed/src/main/java/com/welie/blessed/BluetoothPeripheral.kt:422:41 'getParcelableExtra(String!): T?' is deprecated. Deprecated in Java
w: blessed-android-coroutines/blessed/src/main/java/com/welie/blessed/BluetoothPeripheral.kt:925:32 'setter for value: ByteArray!' is deprecated. Deprecated in Java
w: blessed-android-coroutines/blessed/src/main/java/com/welie/blessed/BluetoothPeripheral.kt:926:36 'writeCharacteristic(BluetoothGattCharacteristic!): Boolean' is deprecated. Deprecated in Java
w: blessed-android-coroutines/blessed/src/main/java/com/welie/blessed/BluetoothPeripheral.kt:1037:28 'setter for value: ByteArray!' is deprecated. Deprecated in Java
w: blessed-android-coroutines/blessed/src/main/java/com/welie/blessed/BluetoothPeripheral.kt:1038:36 'writeDescriptor(BluetoothGattDescriptor!): Boolean' is deprecated. Deprecated in Java
w: blessed-android-coroutines/blessed/src/main/java/com/welie/blessed/BluetoothPeripheral.kt:1159:32 'setter for value: ByteArray!' is deprecated. Deprecated in Java
w: blessed-android-coroutines/blessed/src/main/java/com/welie/blessed/BluetoothPeripheral.kt:1160:40 'writeDescriptor(BluetoothGattDescriptor!): Boolean' is deprecated. Deprecated in Java
w: blessed-android-coroutines/blessed/src/main/java/com/welie/blessed/BluetoothPeripheralManager.kt:118:61 'getter for value: ByteArray!' is deprecated. Deprecated in Java
w: blessed-android-coroutines/blessed/src/main/java/com/welie/blessed/BluetoothPeripheralManager.kt:140:40 'setter for value: ByteArray!' is deprecated. Deprecated in Java
w: blessed-android-coroutines/blessed/src/main/java/com/welie/blessed/BluetoothPeripheralManager.kt:169:57 'getter for value: ByteArray!' is deprecated. Deprecated in Java
w: blessed-android-coroutines/blessed/src/main/java/com/welie/blessed/BluetoothPeripheralManager.kt:209:32 'setter for value: ByteArray!' is deprecated. Deprecated in Java
w: blessed-android-coroutines/blessed/src/main/java/com/welie/blessed/BluetoothPeripheralManager.kt:257:44 'setter for value: ByteArray!' is deprecated. Deprecated in Java
w: blessed-android-coroutines/blessed/src/main/java/com/welie/blessed/BluetoothPeripheralManager.kt:266:40 'setter for value: ByteArray!' is deprecated. Deprecated in Java
w: blessed-android-coroutines/blessed/src/main/java/com/welie/blessed/BluetoothPeripheralManager.kt:447:47 'getter for value: ByteArray!' is deprecated. Deprecated in Java
w: blessed-android-coroutines/blessed/src/main/java/com/welie/blessed/BluetoothPeripheralManager.kt:453:28 'setter for value: ByteArray!' is deprecated. Deprecated in Java
w: blessed-android-coroutines/blessed/src/main/java/com/welie/blessed/BluetoothPeripheralManager.kt:454:38 'notifyCharacteristicChanged(BluetoothDevice!, BluetoothGattCharacteristic!, Boolean): Boolean' is deprecated. Deprecated in Java

```

My solution was to address these by putting in checks for API >=33 and then write the code path for both variations. I'll see what I can do. I'll submit it as part of this PR itself.

**Review by weliem — APPROVED** [review]

**Comment by nisrulz** [comment]
@weliem I was still working on adding some code to this PR, but I see you are already working on it. 

Thanks for merging the PR anyways, it had some simple upgrades to the project.

**Comment by weliem** [comment]
I did a couple of more fixes that had to be done and released a new version.

Thx for your work!

**Pull request merged**
